spring:
    application:
        name: hr-management-server
    servlet:
        multipart:
            max-file-size: 10MB
            max-request-size: 20MB
    datasource:
        url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/hr_management_db_dev}
        username: ${DATABASE_USERNAME:postgres}
        password: ${DATABASE_PASSWORD:pqkiet854A@}
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate.ddl-auto: validate
        show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
    flyway:
        enabled: true
        locations: classpath:db/migration,classpath:db/sampledata
        baseline-on-migrate: true
        baseline-version: 0
server:
    port: ${SERVER_PORT:8080}
logging:
    level:
        root: INFO
        '[org.springframework.security]': DEBUG

# Google Cloud Storage Configuration
gcs:
    bucket-name: ${GCS_BUCKET_NAME:hr-management-bucket}
    project-id: ${GCS_PROJECT_ID:magnetic-clone-478711-i6}
    credentials-path: ${GCS_CREDENTIALS_PATH:classpath:gcs-credentials.json}